# Generated by Django 4.2.11 on 2026-01-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('statut_paiement', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='personnes.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_acte', models.CharField(max_length=100)),
                ('tarif_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=100)),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='billing.facture')),
            ],
        ),
        migrations.CreateModel(
            name='FacturePrestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField()),
                ('prix_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='billing.facture')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.prestation')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='prestations',
            field=models.ManyToManyField(related_name='factures', through='billing.FacturePrestation', to='billing.prestation'),
        ),
    ]
