# Generated by Django 4.2.11 on 2026-01-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('motif', models.TextField()),
                ('statut_rdv', models.CharField(default='Programmé', max_length=20)),
                ('medecin', models.ForeignKey(limit_choices_to={'fonction': 'MED'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='personnes.personnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='personnes.patient')),
            ],
        ),
    ]
