# Generated by Django 6.0.1 on 2026-01-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_rendezvous_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut_rdv',
            field=models.CharField(choices=[('Programmé', 'Programmé'), ('Confirmé', 'Confirmé'), ('Annulé', 'Annulé'), ('Terminé', 'Terminé')], default='Programmé', max_length=20),
        ),
    ]
