# Generated by Django 4.2.11 on 2026-01-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'fonction': 'RES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to='personnes.personnel')),
            ],
        ),
    ]
