# Generated by Django 4.2.11 on 2026-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('assurance', models.CharField(blank=True, max_length=100)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('antecedent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fonction', models.CharField(choices=[('MED', 'Médecin'), ('INF', 'Infirmier'), ('ADM', 'Agent administratif'), ('CAI', 'Caissier'), ('RES', 'Responsable service'), ('DIR', 'Direction'), ('ADMIN', 'Administrateur système')], max_length=5)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('ACT', 'Actif'), ('CON', 'En congé'), ('SUS', 'Suspendu')], default='ACT', max_length=3)),
                ('date_embauche', models.DateField()),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcheAidant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lien_parent', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('patients', models.ManyToManyField(related_name='proches', to='personnes.patient')),
            ],
        ),
    ]
