# Generated by Django 4.2.11 on 2026-01-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnes', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField()),
                ('heure_consultation', models.TimeField()),
                ('diagnostic', models.TextField()),
                ('observations_cliniques', models.TextField(blank=True)),
                ('medecin', models.ForeignKey(limit_choices_to={'fonction': 'MED'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='personnes.personnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='personnes.patient')),
                ('rendezvous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='planning.rendezvous')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescription', models.DateField(auto_now_add=True)),
                ('contenu_medical', models.TextField()),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='medical.consultation')),
            ],
        ),
    ]
